---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "clair3"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::clair3=1.0.8"
