---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "svim"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::svim=2.0.0"
